force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Connected_User__c.field-meta.xml
<CustomField>
    <fullName>Connected_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connected User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee Personal Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Employee Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/Employee_Training__c.object-meta.xml
<CustomObject>
    <label>Employee Training</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Employee Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Training__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Training_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Training_Schedule__c</fullName>
    <label>Training Schedule</label>
    <referenceTo>Training_Schedule__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/Training_Schedule__c.object-meta.xml
<CustomObject>
    <label>Training Schedule</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Schedule__c/fields/Schedule_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Time__c</fullName>
    <label>Schedule Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/fields/Subtopics__c.field-meta.xml
<CustomField>
    <fullName>Subtopics__c</fullName>
    <label>Subtopics</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>This field is topic field.It contain only text.</description>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrainingControllerTest.cls
@isTest
public  class TrainingControllerTest {

@testSetup static void getTrainingRecords()
{

    Employee__c emp =new Employee__c();
    emp.First_Name__c='XYZ';
    emp.Email__c='test@gmail.com';
    emp.Connected_User__c = UserInfo.getUserId();
    insert emp;

    Employee__c emp1 =new Employee__c();
    emp1.First_Name__c='XYZ';
    emp1.Email__c='test@gmail.com';
    insert emp1;

    Training_Schedule__c trainingSchedule = new  Training_Schedule__c ();
    trainingSchedule.Schedule_Time__c= date.today()+5;
    trainingSchedule.Subtopics__c='Introduction Anypoint Platform, Debug Mule Application, Structuring Mule Applications';
    trainingSchedule.Topic__c='Mulesoft';
    insert trainingSchedule;

    Employee_Training__c empTraining =new Employee_Training__c();
    empTraining.Training_Schedule__c= trainingSchedule.Id;
    empTraining.Employee__c = emp.Id;
    insert empTraining;

    Employee_Training__c empTraining1 =new Employee_Training__c();
    empTraining1.Training_Schedule__c= trainingSchedule.Id;
    empTraining1.Employee__c = emp1.Id;
    insert empTraining1;

   
}
@isTest static void runTrainingMethods()
{
   
    Employee__c empRec=[SELECT Id,First_Name__c,Email__c FROM Employee__c LIMIT 1];
    //System.assertEquals(empRec.First_Name__c,'XYZ');

    Training_Schedule__c trainingSchedule = [SELECT Id FROM Training_Schedule__c WHERE Topic__c = 'Mulesoft' LIMIT 1 ];
    Employee_Training__c empTraining1 = [SELECT Id FROM Employee_Training__c LIMIT 1];

   test.startTest();
   TrainingController.getUpcomingTrainings();
   TrainingController.getEnrolledTrainings();
   TrainingController.enroll(trainingSchedule.Id);
   TrainingController.assignToMe(trainingSchedule.Id);
   TrainingController.decline(empTraining1.Id);
   

   test.stopTest();
}
    @isTest static void runExceptions1() {
        test.startTest();
        try{
       TrainingController.getUpcomingTrainings();
        }catch (exception e0) {
            
        }
        test.stopTest();
    }
    @isTest static void runExceptions2() {
        test.startTest();
        try{
       TrainingController.getEnrolledTrainings();
        }catch (exception e0) {
            
        }
        test.stopTest();
    }
    @isTest static void runExceptions3() {
        test.startTest();
        try{
       TrainingController.enroll(null);
        }catch (exception e0) {
            
        }
        test.stopTest();
    }
    @isTest static void runExceptions4() {
        test.startTest();
        try{
       TrainingController.assignToMe(null);
        }catch (exception e0) {
            
        }
        test.stopTest();
    }
    @isTest static void runExceptions5() {
        test.startTest();
        try{
       TrainingController.decline(null);
        }catch (exception e0) {
            
        }
        test.stopTest();
    }
}