force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Connected_User__c.field-meta.xml
<CustomField>
    <fullName>Connected_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connected User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee Personal Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Employee Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/orgChartId__c.field-meta.xml
<CustomField>
    <fullName>orgChartId__c</fullName>
    <externalId>true</externalId>
    <label>orgChartId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Performance_Flag__c.field-meta.xml
<CustomField>
    <fullName>Performance_Flag__c</fullName>
    <label>Performance Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
                <default>true</default>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeePortalControllerTest.cls
@isTest
public class EmployeePortalControllerTest {
    
    @testSetup 
    static void setup() {
        Employee__c empRecord = new Employee__c();
        empRecord.First_Name__c = 'Test Emplyee';
        empRecord.Email__c = 'test@test.com';
        empRecord.Performance_Flag__c = 'Green';
        empRecord.orgChartId__c = 123;
        empRecord.Connected_User__c = UserInfo.getUserId();
        
        insert empRecord;        
    }
    
    @isTest
    static void validateGetEmployeeDetail() {
		Employee__c empRecord = [SELECT Id, First_Name__c FROM Employee__c WHERE First_Name__c = 'Test Emplyee' LIMIT 1];
        System.AssertEquals(empRecord.First_Name__c, 'Test Emplyee');
		test.startTest();
            EmployeePortalController.getEmployeeDetail('Employee', true);
        test.stopTest();
    }
    
    @isTest
    static void getPerformanceFlagTest() {
        Employee__c empRecord = [SELECT Id, First_Name__c, Performance_Flag__c FROM Employee__c WHERE First_Name__c = 'Test Emplyee' LIMIT 1];
        System.AssertEquals(empRecord.Performance_Flag__c, 'Green');
        Test.startTest();
        EmployeePortalController.getPerformanceFlag();
        Test.stopTest();
    }
}