force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <label>IFSC Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/orgChartId__c.field-meta.xml
<CustomField>
    <fullName>orgChartId__c</fullName>
    <externalId>true</externalId>
    <label>orgChartId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/orgChartParentId__c.field-meta.xml
<CustomField>
    <fullName>orgChartParentId__c</fullName>
    <description>org Chart Parent Id</description>
    <label>orgChartParentId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmployeeHierarchyControllerTest.cls
@isTest
public class EmployeeHierarchyControllerTest {
 	@isTest
    public static void GetEmployeeDetails(){
        list<Employee__c> Emplist = New List<Employee__c>();
        
        
            Employee__c Emp = New Employee__c();
            Emp.Name = 'Nidhi';
            Emp.Bank_Account_Number__c = '123456789000';
            Emp.IFSC_Code__c = '0000SBI0908';
            Emp.orgChartId__c = 4;
            Emp.orgChartParentId__c = 5;
            Emp.Active__c = True;
           	Emplist.Add(Emp);
        
        
        Test.StartTest();
        Insert Emplist;
        Test.StopTest();
        
        list<Employee__c> UpdatedEmplist= [Select Id,Name,orgChartId__c,orgChartParentId__c
                                           from Employee__c where Id =:Emplist[0].Id];
        
        system.assertEquals(4,UpdatedEmplist[0].orgChartId__c);
        system.assertEquals(5,UpdatedEmplist[0].orgChartParentId__c);
        EmployeeHierarchyController.getEmployeeDetails();
        
    }

}