force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Leave_Balance__c.field-meta.xml
<CustomField>
    <fullName>Leave_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>It will show the balance leave</description>
    <label>Leave Balance</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>LV-{0000}</displayFormat>
        <label>Leave Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Select Employee</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leaves</relationshipLabel>
    <relationshipName>Leaves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>leave End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <description>The different types of leaves that are include earned leaves, casual leaves and sick leaves</description>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL(Casual leave)</fullName>
            </value>
            <value>
                <fullName>HL(Half-day leave)</fullName>
            </value>
            <value>
                <fullName>OL(one-day leave)</fullName>
            </value>
            <value>
                <fullName>SL/ML(Sick leave/Medical leave)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Leave Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LeaveTriggerHelper.cls
public class LeaveTriggerHelper {
    
    public static void handleUpdateRecord(List<Leave__c> leaves, Map<Id,Leave__c> oldMap) {
        Map<Id,decimal> empIdToLeaveCountMap = getEmpLeaveCount(leaves);
        List<Employee__c> empUpdateList = New List<Employee__c>();
        for (Leave__c leave : leaves) {
            if (empIdToLeaveCountMap.get(leave.Employee__c) != null && (leave.End_Date__c != oldMap.get(leave.Id).End_Date__c || leave.Start_Date__c != oldMap.get(leave.Id).Start_Date__c)) {
                Decimal noOfLeaves = leave.Start_Date__c.daysBetween(leave.End_Date__c) + 1;
                Decimal noOfLeaves2 = oldMap.get(leave.Id).Start_Date__c.daysBetween(oldMap.get(leave.Id).End_Date__c) + 1;
                For (Employee__c empRecord : [SELECT Id, Leave_Balance__c FROM Employee__c WHERE Id IN:empIdToLeaveCountMap.keySet()]){
                   empRecord.Leave_Balance__c = (empRecord.Leave_Balance__c + noOfLeaves2 ) - noOfLeaves; 
                   empUpdateList.add(empRecord);                        
                }
            }
        }
        if (!empUpdateList.isEmpty()){
            update empUpdateList;
        }
    }
    
    public static Map<Id,decimal> getEmpLeaveCount(List<Leave__c> leaves) {
        Map<Id,decimal> empIdToLeaveCountMap = new Map<Id,decimal>();
        for (Leave__c leave : leaves) {
            Decimal noOfLeaves = leave.Start_Date__c.daysBetween(leave.End_Date__c) + 1;
            if (empIdToLeaveCountMap.get(leave.Employee__c) != null) {
                if (leave.Leave_Type__c == 'HL(Half-day leave)') {
                    empIdToLeaveCountMap.put(leave.Employee__c, empIdToLeaveCountMap.get(leave.Employee__c) + noOfLeaves/2);
                } 
                else {
                    empIdToLeaveCountMap.put(leave.Employee__c, empIdToLeaveCountMap.get(leave.Employee__c) + noOfLeaves); 
                }
            } 
            else {
                if (leave.Leave_Type__c == 'HL(Half-day leave)') {
                    empIdToLeaveCountMap.put(leave.Employee__c, noOfLeaves/2);
                } else {
                    empIdToLeaveCountMap.put(leave.Employee__c, noOfLeaves);
                }
            }   
        }
        return empIdToLeaveCountMap;
    }
    
    public static void EmployeeUpdate(Map<Id,decimal> empIdToLeaveCountMap, Boolean isAddition) {
        List<Employee__c> empUpdateList = New List<Employee__c>();
        For (Employee__c empRecord : [SELECT Id, Leave_Balance__c FROM Employee__c WHERE Id IN:empIdToLeaveCountMap.keySet()]){
            if(isAddition){
                empUpdateList.add(new Employee__c(Id=empRecord.Id, Leave_Balance__c=empRecord.Leave_Balance__c - empIdToLeaveCountMap.get(empRecord.Id))); 
            }
            else {
                empUpdateList.add(new Employee__c(Id=empRecord.Id, Leave_Balance__c=empRecord.Leave_Balance__c + empIdToLeaveCountMap.get(empRecord.Id))); 
            }
        }
        if (!empUpdateList.isEmpty()){
            update empUpdateList;
        }
        
    }
    
}