force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Leave_Balance__c.field-meta.xml
<CustomField>
    <fullName>Leave_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <description>It will show the balance leave</description>
    <label>Leave Balance</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>LV-{0000}</displayFormat>
        <label>Leave Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Select Employee</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leaves</relationshipLabel>
    <relationshipName>Leaves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>leave End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <description>The different types of leaves that are include earned leaves, casual leaves and sick leaves</description>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL(Casual leave)</fullName>
            </value>
            <value>
                <fullName>HL(Half-day leave)</fullName>
            </value>
            <value>
                <fullName>OL(one-day leave)</fullName>
            </value>
            <value>
                <fullName>SL/ML(Sick leave/Medical leave)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Leave Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LeaveTriggerTest.cls
@isTest
public class LeaveTriggerTest {
    static testMethod void testInsert() {
        
        Employee__c empRecord = new Employee__c(Leave_Balance__c = 20);
       	insert empRecord;
       
        Leave__c leaveRecord = new Leave__c(Employee__c = empRecord.Id, Start_Date__c = system.today(),
                                            End_Date__c = system.today()+2 , Leave_Type__c = 'HL(Half-day leave)');
        insert leaveRecord;
        
        Leave__c leaveRecord2 = new Leave__c(Employee__c = empRecord.Id, Start_Date__c = system.today(),
                                            End_Date__c = system.today()+2 , Leave_Type__c = 'CL(Casual leave)');
        insert leaveRecord2;
        
        Leave__c insertedRecord = [SELECT Id FROM Leave__c WHERE Id = :leaveRecord.Id LIMIT 1];
        System.assertNotEquals(null, insertedRecord);
        
        Leave__c insertedRecord2 = [SELECT Id FROM Leave__c WHERE Id = :leaveRecord2.Id LIMIT 1];
        
        delete insertedRecord;
        delete insertedRecord2;
        
    }

    static testMethod void testUpdate() {
        Employee__c empRecord = new Employee__c(Leave_Balance__c = 20);
       	insert empRecord;
        Leave__c leaveRecord = new Leave__c(Employee__c = empRecord.Id, Start_Date__c = system.today(),
                                            End_Date__c = system.today()+2 , Leave_Type__c = 'HL(Half-day leave)');
        insert leaveRecord;

        leaveRecord.Start_Date__c = system.today()+3;
        update leaveRecord;
        Leave__c updatedRecord = [SELECT Id,Start_Date__c FROM Leave__c WHERE Id = :leaveRecord.Id LIMIT 1];
        System.assertEquals(system.today()+3, updatedRecord.Start_Date__c);
        delete updatedRecord;
    }

    static testMethod void testDelete() {
        
        Employee__c empRecord = new Employee__c(Leave_Balance__c = 20);
       	insert empRecord;
        Leave__c leaveRecord = new Leave__c(Employee__c = empRecord.Id, Start_Date__c = system.today(),
                                            End_Date__c = system.today()+2 , Leave_Type__c = 'HL(Half-day leave)');
        insert leaveRecord;

        delete leaveRecord;

        List<Leave__c> deletedRecords = [SELECT Id FROM Leave__c WHERE Id = :leaveRecord.Id];
        System.assertEquals(0, deletedRecords.size());
    }
}