force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Connected_User__c.field-meta.xml
<CustomField>
    <fullName>Connected_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connected User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/Employee_Training__c.object-meta.xml
<CustomObject>
    <label>Employee Training</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Employee Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Training__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Training_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Training_Schedule__c</fullName>
    <label>Training Schedule</label>
    <referenceTo>Training_Schedule__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/Training_Schedule__c.object-meta.xml
<CustomObject>
    <label>Training Schedule</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Schedule__c/fields/Schedule_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Time__c</fullName>
    <label>Schedule Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/fields/Subtopics__c.field-meta.xml
<CustomField>
    <fullName>Subtopics__c</fullName>
    <label>Subtopics</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>This field is topic field.It contain only text.</description>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Training Schedules</relationshipLabel>
    <relationshipName>Training_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Schedule__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <formula>Trainer__r.First_Name__c + &quot; &quot; + Trainer__r.Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trainer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrainingController.cls
public with sharing class TrainingController {
    
    @AuraEnabled
    public static List<Training_Schedule__c> getUpcomingTrainings() {
        try {
            return [
                SELECT Id, Name, Schedule_Time__c, Subtopics__c, Topic__c, Trainer_Name__c
                FROM Training_Schedule__c
                WHERE Schedule_Time__c >= TODAY
                 AND Id NOT IN (
                    SELECT Training_Schedule__c 
                    FROM Employee_Training__c 
                    WHERE Employee__c =: getCurrentUserEmployeeId()
                ) ORDER BY Schedule_Time__c LIMIT 10
            ];
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static List<Training_Schedule__c> getEnrolledTrainings() {
        try {
            return [
                SELECT Id, Name, Schedule_Time__c, Subtopics__c, Topic__c, Trainer_Name__c
                FROM Training_Schedule__c
                WHERE Schedule_Time__c >= TODAY
                AND Id IN (
                    SELECT Training_Schedule__c 
                    FROM Employee_Training__c 
                    WHERE Employee__c =: getCurrentUserEmployeeId()
                ) ORDER BY Schedule_Time__c LIMIT 10
            ];
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void enroll(Id trainingId) {
        try {
            insert new Employee_Training__c(
                Employee__c = getCurrentUserEmployeeId(), 
                Training_Schedule__c = trainingId
            );
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static void assignToMe(Id trainingId) {
        try {
            update new Training_Schedule__c(
                Id = trainingId,
                Trainer__c = getCurrentUserEmployeeId()
            );
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void decline(Id trainingId) {
        try {
            delete [
                SELECT Id 
                FROM Employee_Training__c 
                WHERE Employee__c =: getCurrentUserEmployeeId()
                AND Training_Schedule__c =: trainingId
            ];
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    private static Id getCurrentUserEmployeeId() {
        return [SELECT Id FROM Employee__c WHERE Connected_User__c =: UserInfo.getUserId() LIMIT 1].Id;
    }
}