force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Attendanc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>For Employee Select</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/In_Time__c.field-meta.xml
<CustomField>
    <fullName>In_Time__c</fullName>
    <description>Employee In Time.</description>
    <label>In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Out_Time__c</fullName>
    <description>Employee Out time.</description>
    <label>Out Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Base_Pay__c.field-meta.xml
<CustomField>
    <fullName>Base_Pay__c</fullName>
    <description>Employee base pay hourly or salary</description>
    <label>Base Pay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/DA__c.field-meta.xml
<CustomField>
    <fullName>DA__c</fullName>
    <description>Dearness Allowance</description>
    <label>DA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Select Employee</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/HRA__c.field-meta.xml
<CustomField>
    <fullName>HRA__c</fullName>
    <description>House Rent Allowance for Employee</description>
    <label>HRA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Net_Salary__c.field-meta.xml
<CustomField>
    <fullName>Net_Salary__c</fullName>
    <description>Employee Net Salary</description>
    <label>Net Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Connected_User__c.field-meta.xml
<CustomField>
    <fullName>Connected_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connected User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee Personal Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <description>For Employee Code</description>
    <label>Employee Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Employee Name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Employee Last Name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Employee Contact Number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>LV-{0000}</displayFormat>
        <label>Leave Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Select Employee</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leaves</relationshipLabel>
    <relationshipName>Leaves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>leave End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <description>The different types of leaves that are include earned leaves, casual leaves and sick leaves</description>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL(Casual leave)</fullName>
            </value>
            <value>
                <fullName>HL(Half-day leave)</fullName>
            </value>
            <value>
                <fullName>OL(one-day leave)</fullName>
            </value>
            <value>
                <fullName>SL/ML(Sick leave/Medical leave)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Leave Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EmployeePortalDataControllerTest.cls
@isTest
public class EmployeePortalDataControllerTest {
    
    @testSetup static void setup() {
        Employee__c empRecord = new Employee__c(
            Employee_Code__c='E-07',
            First_Name__c = 'Test Employee',
            Last_Name__c='Test',
            Phone__c= '9876543210',
            Email__c = 'test@test.com',
            Connected_User__c = UserInfo.getUserId()
        );
        insert empRecord; 
        
        list<Compensation__c> lstCompensation = new list<Compensation__c>();
        Compensation__c compRecord = new Compensation__c();
        compRecord.Net_Salary__c = 12000;
        compRecord.Base_Pay__c = 'Hourly';
        compRecord.HRA__c = 2000;
        compRecord.DA__c = 2000;
        compRecord.Employee__c = empRecord.Id;
        lstCompensation.add(compRecord);
        insert lstCompensation;
        
        Attendance__c attRecord = new Attendance__c(  
            In_Time__c = System.now(),
            Out_Time__c = System.now(),
            Employee__c = empRecord.Id
        );
        insert attRecord;
        
        Leave__c leaveRecord = new Leave__c(
            Leave_Type__c = 'CL(Casual leave)',
            Start_Date__c =  System.TODAY(),
            End_Date__c = System.TODAY()+3,
            Employee__c = empRecord.Id
        );
        insert leaveRecord;
    }  
    
    @isTest
    static void validateGetDataWhenSingleIsTrue() {
        test.startTest();
        EmployeePortalDataController.DataWrapper empData = EmployeePortalDataController.getData('Employee__c', true, null, null, 1);
        if (empData != null && empData.records != null) {
            System.assertEquals(1, empData.records.size());
        } else {
            System.assert(false, 'empData or empData.records is null');
        }
        test.stopTest();
    }
    
    @isTest
    static void validateGetDataWhenSingleIsFalse() {
        test.startTest();
        EmployeePortalDataController.DataWrapper attData = EmployeePortalDataController.getData('Attendance__c', false, 'In_Time__c', 'ASC', 2);
        if (attData != null && attData.records != null) {
            System.assertEquals(1, attData.records.size());
        } else {
            System.assert(false, 'attData or attData.records is null');
        }
        
        EmployeePortalDataController.DataWrapper holidayData = EmployeePortalDataController.getData('Holiday', false, 'ActivityDate', 'DESC', 3);
        if (holidayData != null && holidayData.records != null) {
            System.assertEquals(3, holidayData.records.size());
        } else {
            System.assert(false, 'holidayData or holidayData.records is null');
        }
        test.stopTest();
    }
}