force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Upload_CV__c.field-meta.xml
<CustomField>
    <fullName>Upload_CV__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload CV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FileUploadController.cls
public with sharing class FileUploadController {

    @AuraEnabled
    public static void uploadFile(Id recordId, String fileName, String base64Data) {

        if (String.isBlank(base64Data) || String.isBlank(fileName)) {
            throw new AuraHandledException('Invalid file data.');
        }


        Blob fileBody = EncodingUtil.base64Decode(base64Data);


        ContentVersion cv = new ContentVersion();
        cv.Title = fileName;
        cv.PathOnClient = fileName;
        cv.VersionData = fileBody;
        insert cv;


        cv = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];


        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv.ContentDocumentId;
        cdl.LinkedEntityId = recordId; 
        cdl.ShareType = 'V'; 
        cdl.Visibility = 'AllUsers';
        insert cdl;

		 Candidate__c candidate = [
            SELECT Id, Position__c , Upload_CV__c 
            FROM Candidate__c 
            WHERE Id = :recordId 
            LIMIT 1
        ];

		List<Job_Application__c> lstJobApplication = [SELECT Id FROM Job_Application__c WHERE Candidate__c =: recordId ];
		if(lstJobApplication.isempty() ) {
			Job_Application__c objJobApplication = new Job_Application__c(
			Candidate__c = recordId, 

            Position__c = candidate.Position__c
       
			);
        insert objJobApplication;
		} 

		    candidate.Upload_CV__c = true;
        update candidate;
		
    }

}