force-app/main/default/objects/Custom_File__c/Custom_File__c.object-meta.xml
<CustomObject>
    <label>Custom File</label>
    <nameField>
        <label>Custom File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_File__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <label>ContentDocumentId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_File__c/fields/Document_Label__c.field-meta.xml
<CustomField>
    <fullName>Document_Label__c</fullName>
    <label>Document Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_File__c/fields/File_Uploaded_2__c.field-meta.xml
<CustomField>
    <fullName>File_Uploaded_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Uploaded 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_File__c/fields/File_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>File_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_File__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Custom Files</relationshipLabel>
    <relationshipName>Custom_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>REV-{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Appraisal__c.field-meta.xml
<CustomField>
    <fullName>Appraisal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Previous organisation Offer Letter</inlineHelpText>
    <label>Offer Letter / Appraisal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Candidate_photo__c.field-meta.xml
<CustomField>
    <fullName>Candidate_photo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate photo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/KYC__c.field-meta.xml
<CustomField>
    <fullName>KYC__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Pan-card &amp; Aadhar card</inlineHelpText>
    <label>KYC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Marksheets__c.field-meta.xml
<CustomField>
    <fullName>Marksheets__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Education documents</inlineHelpText>
    <label>Marksheets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Relieving_Experience_Letter__c.field-meta.xml
<CustomField>
    <fullName>Relieving_Experience_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Relieving/Experience Letter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Salary_Slip_Bank_statement__c.field-meta.xml
<CustomField>
    <fullName>Salary_Slip_Bank_statement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>3 Month Salary Slip / Bank statement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FileUploaderHandler.cls
public with sharing class FileUploaderHandler {
    public static Boolean isUploadComplete = false;

    @AuraEnabled
    public static Boolean uploadFile(String fileName, String parentId, String label, String contentVersionId) {
        try {
            if (String.isBlank(fileName) || String.isBlank(parentId) || String.isBlank(label) || String.isBlank(contentVersionId)) {
                throw new AuraHandledException('Missing required information.');
            }

            ContentVersion version = [
                SELECT Id, ContentDocumentId
                FROM ContentVersion
                WHERE Id = :contentVersionId
                LIMIT 1
            ];

            Id contentDocumentId = version.ContentDocumentId;

            List<Custom_File__c> existing = [
                SELECT Id
                FROM Custom_File__c
                WHERE Review__c = :parentId AND Document_Label__c = :label
                LIMIT 1
            ];
            
            String fileNameWithoutExtension = fileName;
            Integer dotIndex = fileName.lastIndexOf('.');

            if (dotIndex != -1 && dotIndex > 0) {
                fileNameWithoutExtension = fileName.substring(0, dotIndex);
            }

            if (existing.isEmpty()) {
                insert new Custom_File__c(
                    Review__c = parentId,
                    Document_Label__c = label,
                    Name = fileNameWithoutExtension, //fileName,
                    ContentDocumentId__c = contentDocumentId,
                    File_Uploaded__c = true
                );
            } else {
                Custom_File__c record = existing[0];
                record.Name = fileNameWithoutExtension; //fileName;
                record.ContentDocumentId__c = contentDocumentId;
                record.File_Uploaded_2__c = true;
                update record;
            }

            updateReviewFlags(label, parentId);
            return true;

        } catch (Exception ex) {
            throw new AuraHandledException('Upload failed: ' + ex.getMessage());
        }
    }


    private static void updateReviewFlags(String label, Id parentId) {
        Review__c review = [
            SELECT Id, Marksheets__c, Candidate_photo__c, KYC__c, Appraisal__c, 
                   Salary_Slip_Bank_statement__c, Relieving_Experience_Letter__c
            FROM Review__c 
            WHERE Id = :parentId 
        ];

        if (label == 'Cadidate Photo') {
            review.Candidate_photo__c = true;
        } else if (label == 'KYC') {
            review.KYC__c = true;
        } else if (label == 'Marksheet') {
            review.Marksheets__c = true;
        } else if (label == 'Offer Letter / Appraisal') {
            review.Appraisal__c = true;
        } else if (label == 'Relieving/Experience Letter') {
            review.Relieving_Experience_Letter__c = true;
        } else if (label == '3 Month Salary Slip / Bank statement') {
            review.Salary_Slip_Bank_statement__c = true;
        }

        update review;
    }

    @AuraEnabled(cacheable=true)
    public static List<DocumentWrapper> fetchUploadedFileNames(String parentId) {
        List<DocumentWrapper> wrappers = new List<DocumentWrapper>();

        if (String.isBlank(parentId) ) { 
            // System.debug('Invalid or blank parentId provided: ' + parentId + '. Returning empty list.');
            return wrappers; 
        }

        List<Custom_File__c> lstCustomFile = [
            SELECT Document_Label__c, Name, File_Uploaded__c, ContentDocumentId__c, File_Uploaded_2__c
            FROM Custom_File__c 
            WHERE Review__c = :parentId
        ];

        Map<String, ContentVersion> labelToContentMap = new Map<String, ContentVersion>();
        for (ContentVersion cv : [
            SELECT Id, Title, ContentDocumentId
            FROM ContentVersion
            WHERE FirstPublishLocationId = :parentId
            ORDER BY CreatedDate DESC
            LIMIT 100
        ]) {
            labelToContentMap.put(cv.Title, cv); 
        }
        
        for (Custom_File__c objFile : lstCustomFile) {
            String label = objFile.Document_Label__c;
            String name = objFile.Name;

            String contentVersionId = '';
            String contentDocumentIdFromCv = '';
            if (labelToContentMap.containsKey(name)) {
                ContentVersion cv = labelToContentMap.get(name);
                contentVersionId = cv.Id;
                contentDocumentIdFromCv = cv.ContentDocumentId;
             }
             String finalContentDocumentId = String.isNotBlank(objFile.ContentDocumentId__c) ? objFile.ContentDocumentId__c : contentDocumentIdFromCv;
            // String versionId = labelToContentMap.containsKey(name) ? labelToContentMap.get(name).Id : '';
            wrappers.add(new DocumentWrapper(
                label,
                name,
                objFile.File_Uploaded__c,
                objFile.File_Uploaded_2__c,
                contentVersionId,
                finalContentDocumentId
                ));
        }

        return wrappers;
    }

    public class DocumentWrapper {
        @AuraEnabled public String documentLabel { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public Boolean fileUploaded { get; set; }
        @AuraEnabled public Boolean fileUploaded2 { get; set; }
        @AuraEnabled public String contentVersionId { get; set; }
        @AuraEnabled public String contentDocumentId { get; set; }

        public DocumentWrapper(String documentLabel, String name, Boolean fileUploaded, Boolean fileUploaded2, String contentVersionId, String contentDocumentId) {
            this.documentLabel = documentLabel;
            this.name = name;
            this.fileUploaded = fileUploaded;
            this.fileUploaded2 = fileUploaded2;
            this.contentVersionId = contentVersionId;
            this.contentDocumentId = contentDocumentId;
        }
    }

    @AuraEnabled
    public static String getRecordTypeName(Id recordId) {
        try {
            Review__c reviewRecord = [
                SELECT RecordType.DeveloperName 
                FROM Review__c 
                WHERE Id = :recordId 
                LIMIT 1
            ];
            return reviewRecord.RecordType.DeveloperName;
        } catch (Exception ex) {
            return 'No RecordType Found';
        }
    }

    @AuraEnabled
    public static String getBase64File(String contentVersionId) {
        try {
            ContentVersion version = [
                SELECT VersionData 
                FROM ContentVersion 
                WHERE Id = :contentVersionId 
                LIMIT 1
            ];
            return EncodingUtil.base64Encode(version.VersionData);
        } catch (Exception ex) {
            throw new AuraHandledException('Error loading file: ' + ex.getMessage());
        }
    }

    @AuraEnabled
    public static String getFileName(String contentVersionId) {
        try {
            ContentVersion objCV = [
                SELECT Title 
                FROM ContentVersion 
                WHERE Id = :contentVersionId 
                LIMIT 1
            ];
            return objCV.Title;
        } catch (Exception ex) {
            throw new AuraHandledException('Error loading file: ' + ex.getMessage());
        }
    }
}